### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by elizabeth-tilley** [ds4owd-001/md-02-assignments-elizabeth-tilley#1]
It took me longer than it should have, but it was fun! @larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Well done @elizabeth-tilley, and thank you for working through all the tasks. I have added some comments directly on the commit to practice with you how it could look like if you reviewed the work of students on GitHub. It's like the commenting function from MS Word or Google Docs. 

See the column on the right for my added comments: https://github.com/ds4owd-001/md-02-assignments-elizabeth-tilley/commit/021192bd9162a2650469f750e4ea07a30a0fa2ea

You can also close the issue now.
